Updated HOL patch for Isabelle2024
Deducteam/isabelle_dedukti pull request #35
Opened 2024-12-18 07:31 UTC by melanie-taprogge

2024-12-18 07:40 UTC, fblanqui requested changes
Hi Melanie. Thanks for your PR!
But the CI fails. You perhaps need to update the CI script too.
Note also that examples/dkcheck_STTfa.sh is empty. Is it normal?

2024-12-18 07:40 UTC, fblanqui commented on README.md
> +* [Isabelle2024](https://isabelle.in.tum.de)
Please use https://isabelle.in.tum.de/website-Isabelle2024/dist/Isabelle2024_linux.tar.gz

2024-12-18 07:40 UTC, fblanqui commented on README.md
> +      - Download [Isabelle2024](https://isabelle.in.tum.de)
Please use https://isabelle.in.tum.de/website-Isabelle2024/dist/Isabelle2024_linux.tar.gz

2024-12-19 07:25 UTC, melanie-taprogge commented
> Hi Melanie. Thanks for your PR! But the CI fails. You perhaps need to update the CI script too. Note also that examples/dkcheck_STTfa.sh is empty. Is it normal?

You were right, I indeed had to change the CI script, thank you. The CI went through now. 
And the dkcheck_STTfa.sh did not change at all, it was just displayed as a change due to differing permissions, I fixed that too.

2025-11-04 14:34 UTC, merged

2025-11-04 14:34 UTC, fblanqui commented
Thanks Melanie!